# Generated by Django 3.2.6 on 2025-10-05 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_tmp_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_s3', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROCESANDO', 'PROCESANDO'), ('OK', 'OK'), ('FALLA', 'FALLA')], default='PENDIENTE', max_length=12)),
                ('filas', models.IntegerField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga masiva',
                'verbose_name_plural': 'Cargas masivas',
            },
        ),
    ]
